variable "catalog_name" {}
variable "metastore_name" {}
variable "metastore_label" {}
#variable "default_metastore_workspace_id" {}
variable "default_metastore_default_catalog_name" {}
variable "cluster_name" {}
variable "cluster_autotermination_minutes" {}
variable "cluster_num_workers" {}
variable "cluster_data_security_mode" {}
variable "subscription_id" {}
variable "resource_group_name" {}
variable "databricks_workspace_name" {}
variable "storage_account_name" {}
variable "storage_container_name" {}
variable "databricks_access_connector_name" {}
variable "tenant_id" {}    
variable "client_id" {}         
variable "client_secret" {} 
variable "resource_type" {}
variable "spark_version" {}
variable "bricks_sku" {}
variable "location" {}
variable "environment" {}
variable "role_definition_name" {}
variable "bricks_account_tier" {}
variable "bricks_account_replication_type" {}
variable  "brickd_account_kind" {}
