FROM ubuntu:20.04
MAINTAINER Renukaprasad

RUN apt update && apt install default-jdk -y 
RUN apt install maven -y

COPY java-maven-app.tar.gz .
RUN tar -xf java-maven-app.tar.gz
WORKDIR java-maven-app

RUN mvn clean install

CMD ["sh", "scripts/deliver.sh"]
