

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      #AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      TF_VAR_client_id: "0db66497-5372-4be4-a007-f469101331ef"
      TF_VAR_client_secret: "p398Q~Ev4ZIA~AGwJde3XOTNdvyNpNkNz7W1xbzz"
      TF_VAR_subscription_id: "e1a92ee5-04dd-4101-a557-5d049e70d36b"
      TF_VAR_tenant_id: "fead5631-22ec-4323-bbcf-ff9e28657261"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.0

      - name: Configure Azure CLI
        run: az login --service-principal --username $TF_VAR_client_id --password $TF_VAR_client_secret --tenant $TF_VAR_tenant_id

      - name: Initialize Terraform
        working-directory: ./terraform_storageaccount_defender_setting
        run: terraform init --var-file=env.tfvars
        
      - name: Terraform Plan
        working-directory: ./terraform_storageaccount_defender_setting
        run: terraform plan --var-file=env.tfvars
                
      - name: Terraform Apply
        working-directory: ./terraform_storageaccount_defender_setting
        run: terraform apply --var-file=env.tfvars -auto-approve
        
      # # - name: Clean up
      # #   run: terraform destroy terraform plan -var-file=./Terraform\ Script/Storage\ Account/environments/dev/dev.tfvars -chdir=./Terraform\ Script/Storage\ Account/environments/dev

