FROM ubuntu:20.04
MAINTAINER Renukaprasad 
LABEL "projectImage"="Spring-Boot"

RUN apt update && apt -y install openjdk-8-jdk
RUN mkdir rp_dir

WORKDIR rp_dir
COPY spring-boot-rest-example-0.5.0.war .

COPY rp.sh .
EXPOSE 8090
EXPOSE 8091
CMD sh rp.sh
