FROM ubuntu:20.04
MAINTAINER Renukaprasad
LABEL "projectImage"="demo2"

RUN apt update && apt -y install openjdk-8-jdk
RUN mkdir rp_dir

WORKDIR rp_dir
COPY demo2-0.0.1-SNAPSHOT.jar .

COPY rp.sh .
EXPOSE 8080
CMD sh rp.sh

