FROM ubuntu:20.04
MAINTAINER Renukaprasad
LABEL "projectImage"="Spring-Boot"

RUN apt update && apt -y install default-jdk
RUN mkdir rp_dir

WORKDIR rp_dir
COPY demo1-0.0.1-SNAPSHOT.jar .

COPY rp.sh .
EXPOSE 9090
CMD sh rp.sh
