apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}  
type: Opaque
data:
  apiBaseUrl: {{ .Values.env.apiBaseUrl | b64enc | quote }}
  workspaceApiBaseUrl: {{ .Values.env.workspaceApiBaseUrl | b64enc | quote }}
  diApiBaseUrl: {{ .Values.env.diApiBaseUrl | b64enc | quote }}
  uspApiBaseUrl: {{ .Values.env.uspApiBaseUrl | b64enc | quote }}
  assetsApiBaseUrl: {{ .Values.env.assetsApiBaseUrl | b64enc | quote }}
  reportsApiBaseUrl: {{ .Values.env.reportsApiBaseUrl | b64enc | quote }}
  manifestUspUrl: {{ .Values.env.manifestUspUrl | b64enc | quote }}
  manifestDataIntegrationUrl: {{ .Values.env.manifestDataIntegrationUrl | b64enc | quote }}
  manifestAssetsUrl: {{ .Values.env.manifestAssetsUrl | b64enc | quote }}
  manifestReportsUrl: {{ .Values.env.manifestReportsUrl | b64enc | quote }}
  tokenEndpoint: {{ .Values.env.tokenEndpoint | b64enc | quote }}
  revocationEndpoint: {{ .Values.env.revocationEndpoint | b64enc | quote }}
  issuer: {{ .Values.env.issuer | b64enc | quote }}
  redirectUri: {{ .Values.env.redirectUri | b64enc | quote }}
  clientId: {{ .Values.env.clientId | b64enc | quote }}
  logoutUrl: {{ .Values.env.logoutUrl | b64enc | quote }}
  usp_dt_nginx: {{ .Values.env.usp_dt_nginx | b64enc | quote }}
  data_integration_nginx: {{ .Values.env.data_integration_nginx | b64enc | quote }}
  assets_nginx: {{ .Values.env.assets_nginx | b64enc | quote }}
  reports_nginx: {{ .Values.env.reports_nginx | b64enc | quote }}
  index_env: {{ .Values.env.index_env | b64enc | quote }}
